### ISSUE TITLE
Geofancy not listed in App Store anymore

### ISSUE THREAD

**Issue by c--r** [Geofancy/ios-app#25]
Hi, I can't find Geofancy in the (german) iOS App Store anymore when searching for "geofancy" (can only find Geofancy Beacon and other Apps). Is that related to the move to Open Source?

**Comment by kimar** [comment]
Hi, there's been a bug lately introduced by updatin AFNetworking to v2.5.0. A fix is on it's way, but until then I've removed the app from the store so people don't update and render it useless. If you're already affected just send a mail to support@geofancy.com and you'll receive the latest beta ASAP.

**Comment by kimar** [comment]
@c--r Geofancy 1.8.10 just hit the App Store, fixing this issue.

**Comment by bluewalk** [comment]
Confirmed working. Thanks for the quick response!
