### ISSUE TITLE
GET Failure: NSURLErrorDomain error -1012

### ISSUE THREAD

**Issue by bluewalk** [Geofancy/ios-app#26]
After the new 1.8.9 release of Geofancy update I'm getting the error as showed in the screenshot.
Funny part is that it's an error about GET while the app should do a POST.

Possibly related to #25 ?

![screenshot](https://cloud.githubusercontent.com/assets/6522477/11180989/14f0bc02-8c5f-11e5-9322-6dc6f5eecd8c.png)

**Comment by kimar** [comment]
Hi, yeah a fix is already in `master` and has been submitted to Apple. Getting this out asap. I've been updating `AFNetworking` which introduced changes in it's default security policy rendering all SSL requests useless. If you can disable SSL then you can mitigate this issue in the meantime.

Fix version: https://github.com/Geofancy/ios-app/releases/tag/1.8.10

**Comment by bluewalk** [comment]
Thanks for the update, much appreciated!

**Comment by kimar** [comment]
@bluewalk Geofancy 1.8.10 just hit the App Store, fixing this issue.
